@startuml Project
class ImportedCar extends Car {
    -importedOn: Int
    -originalCountry: String
}

class UsedCar extends Car {
    -mileage: Float
    -modifications: List<String>
}

class NewCar extends Car {
    -concessionaire: String
}

Engine *-- Internals
Internals *-- Car

class Car {
    -releaseYear: Int
    -model: String
    -brand: String
    -body: String
    -priceHistory: Dictionary<Int,Float>
    -internals: Internals
}

class Internals {
    -engine: Engine
    -transmission: String
    -4wb: bool
    -powerTrain: String
    -fuelType: String
    -fuelConsumption: Float
}

class Engine {
    -size: Float
    -cylinders: Int
    -inductionType: String
    -horsePower: Int
    -torque: Int
}

class MotorUtility {
    -urls: List<String>
    -getLatestArticle() -> MotorArticle
    -getArticlesWithCar(Car) -> [MotorArticle]
    -openArticle(MotorArticle)
}

class MotorArticle {
    -publishDate: DateTime
    -body: String
    -getAllCars() -> [Car]
}

class WatchListItem implements Watchable {
    -model: String
    -oldPrice: Float
    -newPrice: Float
}

class Watchable {
    -hasChanges: Bool
    -acceptChanges()
    -getChanges()
}
@enduml
