@startuml Project
class ImportedCar extends Car {
    +importedOn: int
    +originalCountry: str
}

class UsedCar extends Car {
    +mileage: float
    +modifications: List<str>
}

class NewCar extends Car {
    +concessionaire: str
}

Engine *-- Internals
Internals *-- Car

class Car {
    +releaseYear: int
    +model: str
    +brand: str
    +body: str
    +priceHistory: Dictionary<int,float>
    +internals: Internals

    +short_description(): str
    +long_description(): str
}

class Internals {
    +engine: Engine
    +transmission: str
    +4wb: bool
    +powerTrain: str
    +fuelType: str
    +fuelConsumption: float
}

class Engine {
    +size: float
    +cylinders: int
    +inductionType: str
    +horsePower: int
    +torque: int
}

class Application {
    +run()
    +onstartup()
    +onclosure()
}

class App extends Application {
    +onselect(evt)
    +showPriceGraph(car)
}
@enduml
